export const options = [
  { value: 'javascript', label: 'JavaScript' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'csharp', label: 'C#' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'go', label: 'Go' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'swift', label: 'Swift' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'c', label: 'C' },
  { value: 'scala', label: 'Scala' },
  { value: 'rust', label: 'Rust' },
  { value: 'perl', label: 'Perl' },
  { value: 'r', label: 'R' },
  { value: 'lua', label: 'Lua' },
  { value: 'bash', label: 'Bash' },
  { value: 'dart', label: 'Dart' },
  { value: 'haskell', label: 'Haskell' },
  { value: 'react', label: 'React' },
  { value: 'angular', label: 'Angular' },
  { value: 'vue', label: 'Vue.js' },
  { value: 'django', label: 'Django' },
  { value: 'spring', label: 'Spring Boot' },
  { value: 'express', label: 'Express.js' },
  { value: 'laravel', label: 'Laravel' },
  { value: 'rails', label: 'Ruby on Rails' },
  { value: 'flask', label: 'Flask' },
  { value: 'nestjs', label: 'NestJS' },
  { value: 'flutter', label: 'Flutter' },
  { value: 'reactnative', label: 'React Native' },
  { value: 'ionic', label: 'Ionic' },
  { value: 'xamarin', label: 'Xamarin' },
  { value: 'electron', label: 'Electron' },
  { value: 'nextjs', label: 'Next.js' },
  { value: 'gatsby', label: 'Gatsby' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'symfony', label: 'Symfony' },
  { value: 'nodejs', label: 'Node.js' },
  { value: 'dotnet', label: '.NET' },
  { value: 'android', label: 'Android' },
  { value: 'ios', label: 'iOS' },
  { value: 'firebase', label: 'Firebase' },
  { value: 'aws', label: 'Amazon Web Services' },
  { value: 'azure', label: 'Microsoft Azure' },
  { value: 'heroku', label: 'Heroku' },
  { value: 'digitalocean', label: 'DigitalOcean' },
  { value: 'netlify', label: 'Netlify' },
  { value: 'vercel', label: 'Vercel' },
  { value: 'docker', label: 'Docker' },
  { value: 'kubernetes', label: 'Kubernetes' },
  { value: 'jenkins', label: 'Jenkins' },
  { value: 'github', label: 'GitHub' },
  { value: 'gitlab', label: 'GitLab' },
  { value: 'bitbucket', label: 'Bitbucket' },
  { value: 'wordpress', label: 'WordPress' },
  { value: 'shopify', label: 'Shopify' },
  { value: 'gcp', label: 'Google Cloud Platform' },
  { value: 'ibmcloud', label: 'IBM Cloud' },
  { value: 'alicloud', label: 'Alibaba Cloud' },
  { value: 'oraclecloud', label: 'Oracle Cloud' },
  { value: 'render', label: 'Render' },
  { value: 'cloudflare', label: 'Cloudflare' },
  { value: 'digitaloceanappplatform', label: 'DigitalOcean App Platform' },
  { value: 'doctl', label: 'DOCTL' },
  { value: 'lambda', label: 'AWS Lambda' },
  { value: 'appengine', label: 'Google App Engine' },
  { value: 'azurefunctions', label: 'Azure Functions' },
  { value: 'cloudrun', label: 'Google Cloud Run' },
  { value: 'mysql', label: 'MySQL' },
  { value: 'mongodb', label: 'MongoDB' },
  { value: 'postgresql', label: 'PostgreSQL' },
  { value: 'sqlite', label: 'SQLite' },
  { value: 'redis', label: 'Redis' },
  { value: 'dynamodb', label: 'Amazon DynamoDB' },
  { value: 'mariadb', label: 'MariaDB' },
  { value: 'couchbase', label: 'Couchbase' },
  { value: 'cassandra', label: 'Apache Cassandra' },
  { value: 'neo4j', label: 'Neo4j' },
  { value: 'oracle', label: 'Oracle Database' },
  { value: 'mssql', label: 'Microsoft SQL Server' },
]
